# Generated by Django 5.2.5 on 2025-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_url',
            field=models.URLField(blank=True, help_text='Alternative to video file', null=True),
        ),
    ]
