# Generated by Django 5.2.5 on 2025-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_uploader', '0002_alter_videopost_video_file_alter_videopost_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion'), ('twitch', 'Twitch')], max_length=50, unique=True),
        ),
    ]
