# Generated by Django 5.2.5 on 2025-08-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_uploader', '0003_alter_platform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='name',
        ),
        migrations.AddField(
            model_name='platform',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('twitch', 'Twitch'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion'), ('snapchat', 'Snapchat'), ('vkontakte', 'VKontakte'), ('odnoklassniki', 'Odnoklassniki'), ('weibo', 'Weibo')], default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
