# Generated by Django 5.0.6 on 2025-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_uploader', '0004_remove_platform_name_platform_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadstatus',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
